name: Build CYD CSI firmware

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with PlatformIO
        uses: nhedlund/platformio-action@v1
        with:
          command: run

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: CYD-2432S028-CSI-firmware
          path: |
            .pio/build/cyd-2432s028/firmware.bin
            .pio/build/cyd-2432s028/bootloader.bin
            .pio/build/cyd-2432s028/partitions.bin
